### ISSUE TITLE
Clicking on the priority bar resets its value to minimum/maximum with no effects

### ISSUE THREAD

**Issue by bagage** [pentix/qjournalctl#21]
When you click on priority bar near a item, for instance just above "error", this toggles the priority to the minimum/maximum. If you click multiple times, the bar changes from min to max to min etc. 
This does not change the actual priority however, since the level of logs displayed is always the same. To make an actual change, you have to slide the bar manually.

I can produce a video record if needed.

**Comment by pentix** [comment]
Hey I guess I get what you mean.
It looks like this goes into the same category as "logs don't update when using the mouse wheel to scroll the slider".

Might be my Qt bindings or some strange behaviour on Qt's side. I will look into this and let you know, but I guess it won't be a 15 minutes fix this time :wink:

**Comment by pentix** [comment]
So -- Turned out it doesn't take much time to make the issue at least "seem irreproducible" :wink: :roll_eyes: 
Could you grab the referenced branch and give it a go to see if the issue still exists? :)

**Comment by bagage** [comment]
I've tested it, it works great indeed :). It definitively fixes the problem, great work!

**Comment by pentix** [comment]
Cool, I'm going to merge it to master then. Thanks for the help! :)
