### ISSUE TITLE
Build fails on Debian 9 Arm64 (4GB machine)

### ISSUE THREAD

**Issue by DanKline** [pentix/qjournalctl#26]
I am attempting to build the app on Debian 9 ARM64 with 4 GB of memory and am getting these "out of memory" errors.  Any suggestions?

> $ make
> /usr/lib/aarch64-linux-gnu/qt5/bin/qmake -spec linux-g++ CONFIG+=release -o Makefile qjournalctl.pro
> In file /build/qtbase-opensource-src-8BZmR5/qtbase-opensource-src-5.7.1+dfsg/include/QtCore/../../src/corelib/tools/qvector.h, line 544: Out of memory
> Makefile:207: recipe for target 'Makefile' failed
> make: *** [Makefile] Aborted

**Comment by pentix** [comment]
Now that's really strange... I have zero experience when it comes to building Qt applications on ARM64, but 4GB really seems more than enough. Google doesn't show anything interesting either, so the only thing that comes to my mind is to try building some Qt example applications and see if they work? Maybe this will reveal if it's an issue to the build process in general or to the modules used in QJournalctl.

**Comment by DanKline** [comment]
I'm trying to build qjournalctl with an 8GB swap... we'll see how that goes.  I'm already consuming 4.7 GB of it.




Get Outlook for Android







On Sat, May 18, 2019 at 4:19 PM -0500, "Patrick Eigensatz" <notifications@github.com> wrote:












Now that's really strange... I have zero experience when it comes to building Qt applications on ARM64, but 4GB really seems more than enough. Google doesn't show anything interesting either, so the only thing that comes to my mind is to try building some Qt example applications and see if they work? Maybe this will reveal if it's an issue to the build process in general or to the modules used in QJournalctl.

**Comment by DanKline** [comment]
It walked through the entire 8 GB swap and over the edge with a single message , "Killed".  I'll try your idea.  Thanks.




Get Outlook for Android







On Sat, May 18, 2019 at 4:19 PM -0500, "Patrick Eigensatz" <notifications@github.com> wrote:












Now that's really strange... I have zero experience when it comes to building Qt applications on ARM64, but 4GB really seems more than enough. Google doesn't show anything interesting either, so the only thing that comes to my mind is to try building some Qt example applications and see if they work? Maybe this will reveal if it's an issue to the build process in general or to the modules used in QJournalctl.

**Comment by pentix** [comment]
Wow, okay. Something else came to my mind: If you have any other system available than the ARM setup, you might as well try to use a g++ toolchain to cross-compile the project? Not sure though, this might end up in the same disaster...

**Comment by DanKline** [comment]
I think I may see what's happening.  My distro of Debian 9 is way behind on the c++ compiler but I'm running the latest qmake.  I think I need to chat with the distro maintainers.  It will take a while.  Thanks for your help.




Get Outlook for Android







On Sun, May 19, 2019 at 3:31 AM -0500, "Patrick Eigensatz" <notifications@github.com> wrote:












Wow, okay. Something else came to my mind: If you have any other system available than the ARM setup, you might as well try to use a g++ toolchain to cross-compile the project? Not sure though, this might end up in the same disaster...

**Comment by DanKline** [comment]
Can I ask a small favor? Can you direct me to a simple sample for g++ and qmake.  I found out my GCC did upgrade to 6.3




Get Outlook for Android







On Sat, May 18, 2019 at 4:19 PM -0500, "Patrick Eigensatz" <notifications@github.com> wrote:












Now that's really strange... I have zero experience when it comes to building Qt applications on ARM64, but 4GB really seems more than enough. Google doesn't show anything interesting either, so the only thing that comes to my mind is to try building some Qt example applications and see if they work? Maybe this will reveal if it's an issue to the build process in general or to the modules used in QJournalctl.

**Comment by DanKline** [comment]
Hi Patrick,  can I ask a favor?  I found out my Debian did update to GCC 6.3 so now I'm back to trying to figure out what is going on.  This is why I need qjournal 




Get Outlook for Android







On Sat, May 18, 2019 at 4:19 PM -0500, "Patrick Eigensatz" <notifications@github.com> wrote:












Now that's really strange... I have zero experience when it comes to building Qt applications on ARM64, but 4GB really seems more than enough. Google doesn't show anything interesting either, so the only thing that comes to my mind is to try building some Qt example applications and see if they work? Maybe this will reveal if it's an issue to the build process in general or to the modules used in QJournalctl.

**Comment by pentix** [comment]
Hi @DanKline 

Try this: [qtexample.tar.gz](https://github.com/pentix/qjournalctl/files/3196704/qtexample.tar.gz)
You can build it by running `qmake qtexample.pro ; make` and see how that goes.

It should compile to a stub demo app then:
![demo](https://user-images.githubusercontent.com/3193006/58003762-bede9800-7ae1-11e9-89d1-a79930c4b0b0.png)

**Comment by pentix** [comment]
Any updates? Were you able to resolve the memory issue?

**Comment by DanKline** [comment]
Not yet... I set up QtCreator and I'm doing the Notepad Example to create a simple test.  I'll get back to you. It's been a little crazy.




Dan




Get Outlook for Android







On Wed, May 22, 2019 at 4:16 AM -0500, "Patrick Eigensatz" <notifications@github.com> wrote:












Any updates? Were you able to resolve the memory issue?

**Comment by DanKline** [comment]
Hey Patrick, I followed your advice and was able to get the QT Notepad app to build, so I know the tool chain works.  I deleted the .pro and make files and rebuilt them with qmake 3.0.  Now I am making progress and not burning through all available memory, but I am running into a build error on make trying to resolve qdialog in aboutdialog.h.  I'm running QT5.  Is this some QT4 verses QT5 issue?

**Comment by DanKline** [comment]
Got it... I needed to add "QT+= widgets" to the newly generated qjournalctl.pro file.  Thanks for your help.

**Comment by pentix** [comment]
Nice to hear! :+1:
