### ISSUE TITLE
No qmake in Fedora

### ISSUE THREAD

**Issue by drizt** [pentix/qjournalctl#38]
I tried to build qjournalctl on Fedora 31.

    $ ./autogen.sh 
    ./autogen.sh: line 3: qmake: command not found

Then I edit autogen.sh and change `qmake` with `qmake-qt5`. Now I can build.
So qjournalctl should check qmake on system and correct qmake name before building.

**Comment by pentix** [comment]
Hi, thanks for reporting!
I was not aware `qmake` was called differently but it seems Fedora tries to separate the Qt4/Qt5 versions better from each other.

I provided a fix in the master branch, I tested it on a few VMs but not under Fedora, feel free to hit me up again if that did not solve your issue :)

**Comment by drizt** [comment]
Now compiling works but I see strange message

````
$ ./autogen.sh 
which: no qmake in (/home/taurus/.local/bin:/home/taurus/.local/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/taurus/.composer/vendor/bin:/home/taurus/develop/mxe/usr/bin:/home/taurus/develop/mxe/usr/bin)
Info: creating stash file /home/taurus/develop/qjournalctl/.qmake.stash
````

**Comment by pentix** [comment]
Thanks for reporting back, `which` seems to generate different output everywhere :)

It should be fixed now!

**Comment by drizt** [comment]
Now works. Thanks!

**Comment by pentix** [comment]
Awesome, thank you!
