### ISSUE TITLE
failed to start after compilation on xubuntu 18.04

### ISSUE THREAD

**Issue by freddii** [pentix/qjournalctl#40]
when i try to start qjournalctl it exits with:
./qjournalctl: /usr/lib/x86_64-linux-gnu/libssh.so.4: no version information available (required by ./qjournalctl) ./qjournalctl: relocation error: ./qjournalctl: symbol ssh_session_is_known_server version LIBSSH_4_5_0 not defined in file libssh.so.4 with link time reference

for installation i used this script:
https://raw.githubusercontent.com/freddii/program_installers/master/install_qjournalctl.sh

**Comment by pentix** [comment]
Hi, it seems as if libssh was not properly installed?
May I ask you to post the output of `ls /usr/lib/libssh*`?

What was the output of your script and were there any errors?

**Comment by pentix** [comment]
Also I am unsure whether installing `libssh-dev` really is required/helpful.
You might get linking/runtime errors due to this...

Could you try to rerun the script without installing `libssh-dev`?

**Comment by freddii** [comment]
ls /usr/lib/libssh*
ls: cannot access '/usr/lib/libssh*': No such file or directory

**Comment by freddii** [comment]
yes works now. I deinstalled libssh-dev and installed it again and then used my script without installing libssh. thanks for you help :)

**Comment by pentix** [comment]
Good to hear :relieved:
