### ISSUE TITLE
[Windows] Fix linker LIBS for Linux build in project file

### ISSUE THREAD

**Issue by pentix** [pentix/qjournalctl#49]
[It turns out ](https://travis-ci.org/github/pentix/qjournalctl/builds/668162515#L731) the Linux build of the windows-build branch currently fails, since qmake adds the VCPKG_Folder path to the linker libraries... 

[The else branch in the project file](https://github.com/pentix/qjournalctl/blob/44a6bb9b52706f29a8d1edeca72e9e0e6ce15f3f/qjournalctl.pro#L82) is somehow not linked to the `CONFIG(x86_64)` section but rather to the `win32:` option, adding the libraries to the linker.

Could you have a look at this? @alacasta

The reason this hadn't been detected earlier is because the CI was actually quite painful to setup and I limited myself to running CI always on the master branch 🙄

**Comment by alacasta** [comment]
I didn't realize it! I saw you fixed it via https://github.com/pentix/qjournalctl/commit/b095cdbd3e64d0f13f4ae49b722bab20d2019f5b

👍

**Comment by pentix** [comment]
Neither did I haha, and nope seems like I broke the Windows build now 🙄 
I added a webhook such that an AppVeyor build is triggered on push/merge, whether GitHub is able to recognize both as tests.

**Comment by alacasta** [comment]
> Neither did I haha, and nope seems like I broke the Windows build now 🙄
> I added a webhook such that an AppVeyor build is triggered on push/merge, whether GitHub is able to recognize both as tests.

It is strange bc it was under a `win32` section as follows

```
win32:
     CONFIG(x86_64) {
    ...
```

**Comment by pentix** [comment]
Right? That's strange behaviour, but I don't know about the `else` in QMake, maybe it refered to the platform. Anyway, it seems to be fixed with above commit (i.e. specifying the `win32:` for all config lines) I only broke my local build :)
