### ISSUE TITLE
bash: qjournalctl: command not found

### ISSUE THREAD

**Issue by ezalivadnyi** [pentix/qjournalctl#65]
Hi! GUI for journalctl is a great idea, and I happy that somebody already realizes it.
I've passed all the installation steps but after running `Run make -j5` i have don't understand how to find the program? 
Why it don't added to my PATH automatically?
Please add instructions to readme.md how to fix it.

OS: Kali Linux
CPU: 4x3HHz
RAM: 8GB

_Sorry if I made any mistakes, it's my first issue on Github._

**Comment by ezalivadnyi** [comment]
I founded that the necessary file (**qjournalctl**) is located in the same directory you had run make command.
So you maybe want to move all the program folder to /opt if already installed it to ~ folder:
`mv ~/qjournalctl /opt/`
And for the topic of this issue - create a symbolic link to make the program visible in PATH and have access from shell:
`sudo ln -s $(pwd)/qjournalctl /usr/bin/qjournalctl`

**Comment by pentix** [comment]
Hi, as you've noticed, there are different targets the Makefile supports. (compile-only, vs. compile-and-install)

I've updated the instructions accordingly.
Thanks for reporting this!
