### ISSUE TITLE
Feature Request: Support loading a journald DB folder

### ISSUE THREAD

**Issue by cordlandwehr** [pentix/qjournalctl#70]
Mostly from the embedded use case, I often get the full copy of the journal/ folder with provides the journald DB at a custom location. It would be great if QJournalCtl could be pointed to another location of the DB, e.g. via command line option or by a UI option.

**Comment by pentix** [comment]
That is an interesting use case! :)

Checking the man page of journalctl, it should be possible to read from those external directories using `-D` or `--directory`; so it shouldn't take too many adjustments; I'll definitely have a look at it!

Thanks for reaching out! :)

**Comment by pentix** [comment]
You should be able to open a custom journal directory using the menu or the shortcut `Ctrl+O` now :relaxed: 
Hope that suits your use case!

**Comment by cordlandwehr** [comment]
Thanks, tested and works nice!

**Comment by pentix** [comment]
Awesome to hear, thanks for the feedback and the idea!
