### ISSUE TITLE
Filter option

### ISSUE THREAD

**Issue by jedi-nz** [pentix/qjournalctl#76]
Hi,

I have installed qjournalctl version 0.6.3 on Ubuntu 21.10.

I was wondering if someone can tell me how to bring up the filter option with regular expressions?

There is nothing in the readme about it and no option to bring it up that I can find.

Below is a picture showing its existence.

Thanks. 
![qjournalctl](https://user-images.githubusercontent.com/38809167/144823280-a334a35f-1e98-40c0-811d-3dda9dd64d2e.png)

**Comment by jedi-nz** [comment]
I found it CTRL f

**Comment by pentix** [comment]
I'm very sorry, I completely missed this issue! :grimacing: 

`CTRL+F` is the way to go, there's still some improvements to this (and the entire filtering) in the pipeline, however
I'm stuck with a pretty annoying bug and I couldn't find time yet to improve things.

Sorry again, hope it still works for you as of now! :)
