### ISSUE TITLE
Build using autogen_and_build.bat  Error with build on windows 10.

### ISSUE THREAD

**Issue by Hennard** [pentix/qjournalctl#77]
Good day, I run the autogen_and_build file but get the following errors:   

C:\Software\vcpkg-master>rem 64 bits

C:\Software\vcpkg-master>if "x86_64" == "x86_64" (qmake qjournalctl.pro CONFIG+=release CONFIG+=x86_64 VCPKG_FOLDER=C:\Software\vcpkg-master )
**'qmake' is not recognized as an internal or external command**,
operable program or batch file.

C:\Software\vcpkg-master>nmake
**'nmake' is not recognized as an internal or external command**,
operable program or batch file.

C:\Software\vcpkg-master>windeployqt release/qjournalctl.exe
**'windeployqt' is not recognized as an internal or external command,**
operable program or batch file.

C:\Software\vcpkg-master>rem 32 bits

C:\Software\vcpkg-master>if "x86_64" == "x86" (
copy C:\Software\vcpkg-master\packages\libssh_x86-windows\bin\ssh.dll release\ssh.dll
 copy C:\Software\vcpkg-master\packages\pthreads_x86-windows\bin\ssh.dll release\pthreadVC3.dll
)

C:\Software\vcpkg-master>rem 64 bits

C:\Software\vcpkg-master>if "x86_64" == "x86_64" (
copy C:\Software\vcpkg-master\installed\x64-windows\bin\ssh.dll release\ssh.dll
 copy C:\Software\vcpkg-master\installed\x64-windows\bin\pthreadVC3.dll release\pthreadVC3.dll
)
The system cannot find the path specified.
        0 file(s) copied.
The system cannot find the path specified.
        0 file(s) copied.

C:\Software\vcpkg-master>del release\*.obj
The system cannot find the file specified.

C:\Software\vcpkg-master>del release\*.cpp
The system cannot find the file specified.

C:\Software\vcpkg-master>REM Restore the new path

**Comment by pentix** [comment]
Hi there!

It looks like the script was not able to find the Qt development binaries. It might be the case that you installed another (newer) version on your system (somewhere in `C:\Qt\....\` for example)

In that case, make sure to adjust the path in `autogen_and_build.bat` on line 16
before running the script:

https://github.com/pentix/qjournalctl/blob/16b26c9ed7077a659abce793509dd2984d5885d1/autogen_and_build.bat#L16

I hope this fixes your problems, feel free to reach out again if it still doesn't work!
