### ISSUE TITLE
Show journal entries page can't be maximized

### ISSUE THREAD

**Issue by Yournished** [pentix/qjournalctl#8]

**Comment by pentix** [comment]
Hi, thanks for the feedback!

What page exactly do you mean cannot be maximized? Do you refer to the main window, when writing about the "journal entries page"?

This one?
![Main Window](https://camo.githubusercontent.com/770dca611ba308ea7808d059657e1c846a3f6ff1/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f33643762613562346436383434383964623431383462356364393737343363392e706e67)

**Comment by pentix** [comment]
Is this still a thing? I don't understand what you mean by the information you provided.
