### ISSUE TITLE
Systemd 251 crashes

### ISSUE THREAD

**Issue by GaVenga** [pentix/qjournalctl#81]
QJournalctl 0.6.3 on Manjaro (unstable) --> Systemd 251 ==> crashes "list all available boots".

**Comment by GaVenga** [comment]
qjournalctl                                                                                                                                                               
zsh: segmentation fault (core dumped)  qjournalctl
---------------------------------------------------------------------------------------------------
sudo qjournalctl                                                                                                                                                     [139]
[sudo] Passwort für xxxxxxx: 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QMetaObject::connectSlotsByName: No matching signal for on_find_keyshortcut_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_escape_keyshortcut_triggered()
QProcess: Destroyed while process ("journalctl") is still running.
---------------------------------------------------------------------------------------------------
(small part only)
systemd-coredump[1671]: Process 1569 (qjournalctl) of user 1000 dumped core.
                                                
                                                Module linux-vdso.so.1 with build-id 12dbba44d2f4bad7316cafe2f49495f3083628d5
                                                Module libncursesw.so.6 with build-id b9917757481e6fa6097e2a1f31f5bb5eaf138c4e
                                                Module libedit.so.0 with build-id 4b0babfcad161c2ad0af6e59e2493258db23a331
                                                Module libvulkan.so.1 with build-id 198212a538d4e3b290530d75a0614e803b03d39e
                                                Module libdrm_nouveau.so.2 with build-id af8afb2331ac08c52132102ecbdc6076a8eb4c6f
                                                Module libdrm_amdgpu.so.1 with build-id 8eb3977b830f3012d9ead7b4def5f4d2f38ec688
                                                Module libelf.so.1 with build-id c09e357a1a3b061bf219bcfb243ca31b175e77fa
                                                Module libdrm_radeon.so.1 with build-id 43e0aecc70c4ce905ba35c948e1c9a5d999b14c0
                                                Module libsensors.so.5 with build-id dc8b2c1c0d8525411aca188ea3cc3fb86d381d30
                                                Module libLLVM-13.so with build-id 90a760361bef9d2de117d7e696dad26fc4cb24f4
                                                Module radeonsi_dri.so with build-id e00d40d9af60ae8c5890e421bd6414c8479b6bce
                                                Module libxshmfence.so.1 with build-id d9b3ce4edb0b6a0818bcc57dda020d2da5e3c895
                                                Module libxcb-present.so.0 with build-id 8ed389d9cd6ad7110fbb00c93b32e0efaa71a6b1
                                                Module libxcb-dri3.so.0 with build-id 088c750254cc139e7d62b8a3fc7795a138447ccf
                                                Module libXxf86vm.so.1 with build-id b8b37b0c66be0a760a8491e3c86a00c4efdc825d
                                                Module libxcb-dri2.so.0 with build-id 7bde0abc84135ae6258a8d1d130864071c2cc327
                                                Module libdrm.so.2 with build-id 00816f0a71c7e4e388c10db6245dbb9c031732a9
                                                Module libglapi.so.0 with build-id 7320999a92c1f2c0f14ab2485507d54d7317bcc0
                                                Module libGLX_mesa.so.0 with build-id d3d9aa7a3a9daef558ce72ea111a64a183efe8cf
                                                Module libxcb-glx.so.0 with build-id 71d5b6691f53a235696da49ffa2178d643ecc228
                                                Module libqxcb-glx-integration.so with build-id 94a60c6db58e9174d381312b0bcc97a5f7f4c7fd
                                                Module libQt5Svg.so.5 with build-id 74fc2741f02d4a0e0f7585a36f607656d18361bb
                                                Module libqsvg.so with build-id 0993859f4fc44079d066000de1a17b7404cd57bd
                                                Module libresolv.so.2 with build-id 89a368a6ad1b392d126a2a5beb9c2f61ade00279
                                                Module libkeyutils.so.1 with build-id ac405ddd17be10ce538da3211415ee50c8f8df79
                                                Module libkrb5support.so.0 with build-id 36db7c21bc57a9b934ad2d3463782db9fef4af07
                                                Module libcom_err.so.2 with build-id 358b783c9b3d12ba8248519ea2e7f3da4c4e0297
                                                Module libk5crypto.so.3 with build-id f1c113fea46023cdf62c7e51cb643c45831abdd5
                                                Module libkrb5.so.3 with build-id 9350783c946d77aec8ee8fd9c6bc12f4f7b72be9
                                                ......

**Comment by GaVenga** [comment]
Another thing:
Wrong Time in "List all available boots" - Timestamp displayed two Hours in the future - (MESZ) = UTC + 2 Stunden
Qjournalctl lists: UTC instead.
O.k. "Filter by syslog identifiers" NEVER worked, but I export the journal anyway if needed...

**Comment by pentix** [comment]
> QJournalctl 0.6.3 on Manjaro (unstable) --> Systemd 251 ==> crashes "list all available boots".

I was not able to reproduce the crash on systemd 251.2, however no boot logs were shown at all, and I fixed this in commit 6358207. Could you check whether this also fixes your crashing issue?


> Wrong Time in "List all available boots" - Timestamp displayed two Hours in the future - (MESZ) = UTC + 2 Stunden

I'll split this up into a separate issue, thanks!

> "Filter by syslog identifiers" NEVER worked, but I export the journal anyway if needed...

I just tested this, and it still seems to work. For example filtering for qjournalctl's / Qt's own debug messages works fine. Are you able to see what you're looking for using the plain `journalctl`?

**Comment by GaVenga** [comment]
Filtered journal:
filtering for "failed" results in:
Selected journal seems to be empty using selected filter settings.
although there are 4 messages in unfiltered journal - may be result of the UTC-bug??
